services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-local
    network_mode: "host"
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ./ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui-local
    network_mode: "host"
    environment:
      - OLLAMA_BASE_URL=http://localhost:11434
      - PORT=8090
    depends_on:
      - ollama
    volumes:
      - ./open_webui_data:/app/backend/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
